apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.storage }}
  storageClassName: {{ .Values.postgres.pvc.storageClassName }}