apiVersion: v1
kind: Service
metadata:
  name: prod-service
spec:
  selector:
    app: prod-app
  type: NodePort
  ports:
    - port: {{ .Values.prod.port }}
      targetPort: {{ .Values.prod.targetPort }}
      nodePort: {{ .Values.prod.nodePort }}
      protocol: TCP
