apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-deployment
spec:
  replicas: {{ .Values.prod.replicas }}
  selector:
    matchLabels:
      app: prod-app
  template:
    metadata:
      labels:
        app: prod-app

    spec:
      containers:
        - name: prod-app
          image: {{ .Values.prod.image }}
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB
                  name: postgres-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: postgres-secret